### ISSUE TITLE
RFC7662: Why 'username' instead of 'preferred_username'?

### ISSUE THREAD

**Issue by bjmc** [jricher/oauth-spec#111]
I was just wondering why RFC7662 uses `username` instead of `preferred_username` [as in the OpenIDConnect spec?](https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims) Most of the other fields in the introspection response are nicely congruous with claims in the OIDC id_token. Did you just prefer `username` because it's more concise?

**Comment by jricher** [comment]
They're different uses, really. It's conferring the username of the resource owner at the AS, not the username that the user would prefer to use at an RP.
